### ISSUE TITLE
análisis de modelo para evaluación unificado de los apis evaluacion_inscripcion y evaluacion_crud, hablar con grupo de docencia para api de evaluación de productos de docentes

### ISSUE THREAD

**Issue by corio27** [udistrital/evaluaciones_mongo_crud#1]
- [x] Verificar funcionamiento de apis
 - [x] Ver documentación de lineamientos para creación de apis
 - [x] Ver documentación de lineamientos para refactorización de apis
 - [x] Creación de propuestas para modelo unificado

**Comment by JocoolQ** [comment]
Propuesta de modelo de evaluación para api mongo:

![evaluacion_mongo4](https://user-images.githubusercontent.com/24370138/101698963-631f8b00-3a48-11eb-9ebd-4625f40a5671.png)
