### ISSUE TITLE
Realizar capacitación para el manejo de filtros avanzados del api de evaluaciones mongo crud

### ISSUE THREAD

**Issue by corio27** [udistrital/evaluaciones_mongo_crud#12]

**Comment by JocoolQ** [comment]
Se adjunta [enlace](https://slides.com/jonathanstevencaperaquintana/deck) de la presentación  elaborada junto con @criss201x

**Comment by criss201x** [comment]
Se adjunta [Link ](https://drive.google.com/file/d/1ePxYN1LOeWZDihS1mHt-h9mPoabmrlrj/view?usp=sharing) de la grabación de la capacitación realizada junto con @JocoolQ
