### ISSUE TITLE
Generar pipeline para apis realizados con framework de nodejs

### ISSUE THREAD

**Issue by corio27** [udistrital/evaluaciones_mongo_crud#4]
- [x] Analizar requisitos para despliegue de API en producción
 - [x] Generar entrypoint.sh para ejecución del compilado de API 
 - [x] Generar Dockerfile para despliegue de API en AWS
 - [x] Realizar merge de la rama develop con release
 - [x] Verificar funcionamiento de API en producción

**Comment by JocoolQ** [comment]
Junto con @criss201x se analizan los requisitos del API elaborado con el framework NestJS para su despliegue en producción.

El API genera un compilado del proyecto y realiza un transpilado de los archivos Typescript a Javascript, el cual se genera en la ruta /dist sobre la raíz del proyecto.

* Para generar el compilado se ejecuta la siguiente instrucción:
```shell
nest build
```
* Luego de que haya sido generada la compilación en la ruta /dist se ejecuta el siguiente comando para correr el proyecto:
```shell
node dist/main
```
**Nota:** Se identifica que para correr el proyecto se requiere del contenido de la carpeta /dist y de los paquetes npm instalados en la ruta /node_modules

**Comment by JocoolQ** [comment]
Junto con @criss201x se crea el archivo entrypoint.sh que contiene las sentencias de los pasos respectivos en el pipeline para la ejecución del proyecto.

![entrypoint](https://user-images.githubusercontent.com/24370138/104646159-126e0400-567e-11eb-9f4c-99459d3e6245.PNG)

**Comment by JocoolQ** [comment]
Junto con @criss201x se crea archivo Dockerfile para despliegue de API en AWS.

![Dockerfile image](https://user-images.githubusercontent.com/24370138/104646555-9627f080-567e-11eb-9ca9-4663cf542534.PNG)

**Comment by JocoolQ** [comment]
Junto con @BrayanB24 se realiza [merge](https://github.com/udistrital/evaluaciones_mongo_crud/pull/8) de la rama develop a release y se verifica funcionamiento del API en producción
