### ISSUE TITLE
Generar swagger.json para apis generados con NestJS

### ISSUE THREAD

**Issue by corio27** [udistrital/evaluaciones_mongo_crud#7]

**Comment by JocoolQ** [comment]
Junto con @criss201x se añade la implementación de los requisitos necesarios para la generación del archivo swagger.json, dentro del archivo main.ts del proyecto.

![Swagger](https://user-images.githubusercontent.com/24370138/104648161-bfe21700-5680-11eb-9171-d95ffce45405.PNG)

**Comment by criss201x** [comment]
Se adjuntan imágenes del swagger en funcionamiento 
![Captura de pantalla de 2021-01-14 15-49-18](https://user-images.githubusercontent.com/57843585/104648368-059edf80-5681-11eb-9f03-7778045aa0b7.png)
![Captura de pantalla de 2021-01-14 15-49-33](https://user-images.githubusercontent.com/57843585/104648407-12bbce80-5681-11eb-80af-c867bcb458ef.png)
